language: java
jdk:
- openjdk7
- oraclejdk8
- oraclejdk7
script: mvn install -B -V
notifications:
  slack:
    secure: VnWXoZIYDFYHzPvW+nrUMhkSVZhR2wiU6cuRJzM7ag+EG9TTYMn5nWK0fVxB6mlQvlf/qF6qVvN6pBsHyUsFcHVhaH1cy7fECMBIYjGUloLHUuYwnxaXEsvGGYVRXKPVy9eyCuL9vAwZLhAt/XcNEHcEwrYMGbabrGwc50J566MOsBUh+iSlNk5+aWylpJk/D8je5KV3mNiQSDh+e/s18LEeFeJ9RChxxo/lMz8EiaNUvmAiyylHuSb9DkTGGJzwShKMMB6iNTb8YtBI3NNEAR3H8l7hqYrffpbFTSVbXfaF3C1FVnd9eI4MmYEaX6YY0LMgSqIq1ApbMFu9qzOkx+KYNySz4RjsmpkjESxAaAf74nVJRYaplCI82s5P1082aAzPM3T+OWHQCbbBBeH2pbHLlaO2CD6wn4S0j4Dhx/HMonAPl4B8Mh3kA0qj/mIswsVMUWcC92grNACOYu5v33BUg9p6Y6s01LmH5UmAoWptXNq9DhhY9vOi35F6uw6diauksD1TLAJrex44UUn8jDN9+zto7Ii5TPKUfSmmfKt4deQolyxvKsVLWKR4+44No65Vo683Wj1EyPppfvX+FZhdbjJ29DB/s8qDSlgtTMUcbyuKfjcIsZ0QzuaqUdIiqsXJqIRav+gUU0wPr16Pbxdpe53nh2uPjvp8YviOdvA=
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: target/*.jar
  on:
    tags: true
  api_key:
    secure: ZeLlVbNh9bkqvX+XarKwWRznwuCljEf5RBAs3O0buRDKNzd3ddZ/5Qly+Fq8lCWkarp10dXHCZxCmwAMAA/9w0gJGDhXGKg0ayawbZdLDCXmaCeN4n5Wz0UQkk8/4AISgjdF6Hz7iPDEZ0g4mOT62qD9r9uE2+OmVWdBW+uCpFERE6WhH1d7xWFyO+gIPOLSD5yzUHNx7Xww3+79mIUw9GKIljSm0o8MN/CBJApD2J+XlEI0l49tULZsKcktrNYD64kV42c/ey7jYaasbwZqJgNw0b01k99p69bfV6TuX1rSmXQXbL3NUBX7N5D5hR3gxBD2S/XlW7p1rpuXfWTKUS0qx+YY3Bf1fZy4bD7TJlMZSQIn24c5lD3VnpseyMSC9Erd9DznVbj8eYfuFAZErL80ObOuMRGGnHRkuBiL71YkLTLj0wN5dzE+usFPfkM13977ISu4eDPeDIX6/ZoiSmGxJDauREeJPREwQL8Wgfk+RDczONYDawJGZGraeE5sDIsCpdowQVXhAfO/UgagJFYGwsPQAZiX+PBr8+BpmJ/fgp1nuAAodCbwxycAvwNSVYCXB3QKwLRgKx/9bYgV18noX22TgDP3i0DZ9ydEn1pPq5bu3OJvdZC189y7uVOdHnRSkOa0O8DhImQ/DbGRjMYvxBSdn8tNmXd1XsN355w=
